- name: Add Logstash repository
  apt_repository:
    repo='deb http://packages.elasticsearch.org/logstash/1.3/debian stable main'
    state=present
    update_cache=yes

- name: Install Logstash
  apt: pkg={{ item }} update_cache=yes
  with_items:
  - logstash

- name: Copy the logstash configuration files
  template: src={{ item }}.j2 dest=/etc/logstash/conf.d/{{ item }}
  with_items:
  - 0mysql.conf
  - 0nginx.conf
  - 0php-fpm.conf
  - 0mongodb.conf
  - 9logstash.conf
  notify:
  - restart logstash

- name: Enable logstash and logstash-web to start as a service
  lineinfile: dest=/etc/default/{{ item }} regexp="^START=" line="START=yes"
  with_items:
  - logstash
  - logstash-web
  notify:
  - restart logstash
  - restart logstash-web

- name: Create the logstash grok patterns dir
  file:
    path={{ logstash_patterns_dir }}
    state=directory
    mode=0755
    owner=vagrant
    group=vagrant

- name: Copy the logstash grok patterns file
  copy:
    src=logstash_patterns
    dest={{ logstash_patterns_dir }}/extra
    mode=0755
    owner=vagrant
    group=vagrant


