- name: Add the Ealsticsearch repository key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add Elasticsearch repository
  apt_repository:
    repo='deb http://packages.elasticsearch.org/elasticsearch/1.3/debian stable main'
    state=present
    update_cache=yes

- name: Install Elasticsearch
  apt: pkg={{ item }} update_cache=yes
  with_items:
  - openjdk-7-jre-headless
  - elasticsearch

- name: Configure elasticsearch to start on boot and start it
  service: name=elasticsearch enabled=yes state=started

- name: Install elasticsearch plugins
  command:
    /usr/share/elasticsearch/bin/plugin -install {{ item.name }}
    creates=/usr/share/elasticsearch/plugins/{{ item.dir }}
  with_items:
  - { name: mobz/elasticsearch-head, dir: head }
  - { name: lukas-vlcek/bigdesk, dir: bigdesk }
  - { name: royrusso/elasticsearch-HQ, dir: HQ }
  - { name: karmi/elasticsearch-paramedic, dir: paramedic }