- name: Install Xdebug extension from PECL
  php_package: mode=pecl name=xdebug state=present

- name: Create the xdebug remote log dir
  file:
    path=/var/log/xdebug
    state=directory
    mode=0755
    owner=vagrant
    group=vagrant

- name: Check if Mongo extension is already installed
  command: pecl list mongo
  register: mongo_extension_info
  ignore_errors: yes

- name: Install Mongo extension from PECL and build it without Cyrus SASL
  shell: yes no | pecl install mongo
  when: "'not installed' in mongo_extension_info.stdout"

- name: Install version 2.0.1 of memcached PECL package
  php_package:
    mode=pecl
    name=memcached
    version='2.0.1'
    state=present

- name: Copy the php-fpm init script
  copy:
    src=php-fpm
    dest=/etc/init.d/php-fpm
    mode=0755

- name: Configure php-fpm to start on boot
  service: name=php-fpm enabled=yes

- name: Create PHP configuration directories
  file:
    path=/etc/php/fpm/conf.d
    state=directory
    mode=0755

- name: Copy PHP configuration files
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
  - { src: 'php.ini', dest: '/etc/php/fpm/' }
  - { src: 'xdebug.ini', dest: '/etc/php/fpm/conf.d/' }
  - { src: 'memcached.ini', dest: '/etc/php/fpm/conf.d/' }
  - { src: 'mongo.ini', dest: '/etc/php/fpm/conf.d/' }
  - { src: 'opcache.ini', dest: '/etc/php/fpm/conf.d/' }
  notify:
    - restart php-fpm

- name: Copy the PHP-FPM configuration file
  template: src=php-fpm.conf.j2 dest=/etc/php/fpm/php-fpm.conf
  notify:
    - restart php-fpm

- name: Remove the php-fpm.conf example file, installed with php
  file: path=/etc/php-fpm.conf.default state=absent

- name: Create the PHP-FPM logs directory
  file:
    path={{ php_fpm_log_dir }}
    state=directory
    mode=775
    owner=vagrant
    group=vagrant

- name: Create the PHP-FPM logs directory
  file:
    path={{ php_fpm_log_dir }}/www.log.slow
    state=touch
    mode=664
    owner=vagrant
    group=vagrant

- name: Install composer
  shell:
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin && mv /usr/bin/composer.phar /usr/bin/composer
    creates=/usr/bin/composer